spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres #container name for postgres
  rabbitmq:
    host: rabbitmq #container name for rabbitmq
  kafka:
    properties:
      security.protocol: "SSL"
    bootstrap-servers: kafka:9093 #KAFKA_ADVERTISED_LISTENERS SSL
    ssl:
      trust-store-location: file:/certs/kafka.client.truststore.jks #mounted file
      trust-store-password: "Test123"
      protocol: TLSv1.2
    consumer:
      bootstrap-servers: kafka:9093
      group-id: demo-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      ssl:
        trust-store-location: file:/certs/kafka.client.truststore.jks
        trust-store-password: "Test123"
        protocol: TLSv1.2
    producer:
      bootstrap-servers: kafka:9093
      ssl:
        trust-store-location: file:/certs/kafka.client.truststore.jks
        trust-store-password: "Test123"
        protocol: TLSv1.2
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

